import { COLORS } from '@/constants/colors';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  root: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
  },
  header: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    overflow: 'hidden',
  },
  backPlaceholder: {
    width: 32,
    height: 32,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  animatedBody: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 136,
    gap: 12,
  },
  formContainer: {
    paddingBottom: 136,
    gap: 10,
  },
  profileCard: {
    marginTop: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(124, 148, 186, 0.20)',
    paddingVertical: 14,
    alignItems: 'center',
    overflow: 'hidden',
  },
  profileCardCompact: {
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(124, 148, 186, 0.20)',
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 8,
    overflow: 'hidden',
  },
  avatarOuter: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#1B2B4D',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  profileName: {
    color: '#EAF2FF',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 5,
  },
  profileLocation: {
    color: '#7E90AE',
    fontSize: 11,
    marginTop: 2,
  },
  sectionTitle: {
    color: '#A0B0CA',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  menuGroup: {
    gap: 8,
  },
  rowCard: {
    height: 48,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: '#22324F',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    overflow: 'hidden',
  },
  rowPressed: {
    opacity: 0.88,
  },
  rowIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#1A2946',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  rowLabel: {
    flex: 1,
    color: '#DFE7F5',
    fontSize: 12,
    fontWeight: '600',
  },
  rowArrow: {
    marginLeft: 8,
  },
  dangerRow: {
    height: 46,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 61, 79, 0.08)',
    borderWidth: 1,
    borderColor: '#4A2733',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexDirection: 'row',
    marginTop: 6,
    overflow: 'hidden',
  },
  dangerText: {
    color: '#FCA5A5',
    fontSize: 12,
    fontWeight: '700',
  },
  logoutButton: {
    height: 46,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: '#243656',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 2,
    overflow: 'hidden',
  },
  logoutText: {
    color: COLORS.accent,
    fontSize: 12,
    fontWeight: '700',
  },
  inputLabel: {
    color: '#AFC1DC',
    fontSize: 11,
    fontWeight: '600',
    marginTop: 2,
  },
  input: {
    height: 44,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#253856',
    backgroundColor: 'rgba(255,255,255,0.03)',
    color: '#F0F5FF',
    fontSize: 14,
    paddingHorizontal: 12,
  },
  messageInput: {
    minHeight: 92,
    paddingTop: 10,
  },
  primaryButton: {
    marginTop: 8,
    height: 44,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  primaryButtonText: {
    color: '#F4F8FF',
    fontSize: 12,
    fontWeight: '700',
  },
  buttonPressed: {
    opacity: 0.84,
  },
  helpText: {
    color: '#91A3BF',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 16,
  },
  faqCard: {
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: '#22324F',
    paddingHorizontal: 12,
    paddingVertical: 12,
    overflow: 'hidden',
  },
  faqQuestionWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  faqQuestion: {
    color: '#E5ECF9',
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  faqAnswer: {
    color: '#A0B1CC',
    fontSize: 11,
    lineHeight: 17,
    marginTop: 8,
  },
  policyHeading: {
    color: '#E6EEFC',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 6,
  },
  policyParagraph: {
    color: '#A6B5CC',
    fontSize: 14,
    lineHeight: 19,
  },
  policyBullet: {
    color: '#A6B5CC',
    fontSize: 14,
    lineHeight: 19,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(5,10,22,0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  modalCard: {
    width: '100%',
    maxWidth: 280,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#374765',
    backgroundColor: 'rgba(255,255,255,0.04)',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 14,
    paddingBottom: 16,
    overflow: 'hidden',
  },
  modalIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#47536A',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    color: '#F3F7FF',
    fontSize: 18,
    fontWeight: '700',
  },
  modalSubtitle: {
    color: '#A2B1C9',
    fontSize: 11,
    marginTop: 4,
    marginBottom: 14,
  },
  modalActions: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
  },
  modalCancel: {
    flex: 1,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#4A5874',
    backgroundColor: '#2A3448',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalDelete: {
    flex: 1,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCancelText: {
    color: '#E5ECF8',
    fontSize: 11,
    fontWeight: '600',
  },
  modalDeleteText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '700',
  },
  avatarImage: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#D9D9D9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF22',
  },
});
